/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as counterSol from './Counter.sol/index.js';
export type { counterSol };
import type * as gasDrainTrapSol from './GasDrainTrap.sol/index.js';
export type { gasDrainTrapSol };
import type * as gasTrapSol from './GasTrap.sol/index.js';
export type { gasTrapSol };
export * as factories from './factories/index.js';
export type { Counter } from './Counter.sol/Counter.js';
export { Counter__factory } from './factories/Counter.sol/Counter__factory.js';
export type { GasDrainTrap } from './GasDrainTrap.sol/GasDrainTrap.js';
export { GasDrainTrap__factory } from './factories/GasDrainTrap.sol/GasDrainTrap__factory.js';
export type { GasTrap } from './GasTrap.sol/GasTrap.js';
export { GasTrap__factory } from './factories/GasTrap.sol/GasTrap__factory.js';