/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as counterSol from './Counter.sol/index.js';
export * as gasDrainTrapSol from './GasDrainTrap.sol/index.js';
export * as gasTrapSol from './GasTrap.sol/index.js';